spring:
  application:
    name: "@project.artifactId@"
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/Mahgald/java-configserver-repository.git
          search-paths:
          - 'java-ms*'
info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: ${spring.profiles.active}
  
server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/